var n1 = prompt("Informe o primeiro valor inteiro: ")
var n2 = prompt("Informe o segundo valor inteiro: ")
var n3 = prompt("Informe o terceiro valor inteiro: ")
var n4 = prompt("Informe o quarto valor inteiro: ")
var soma = parseInt(n1) + parseInt(n2) + parseInt(n3) + parseInt(n4)
document.write("A soma dos quatros numeros é: ", soma)
